SRC_DIR=./src/
ALL:
	
	g++ -o server ${SRC_DIR}activeclients.cpp ${SRC_DIR}logthread.cpp ${SRC_DIR}mainthread.cpp ${SRC_DIR}message.cpp ${SRC_DIR}notifythread.cpp ${SRC_DIR}queue.cpp ${SRC_DIR}senderthread.cpp -lpthread

clean:
	rm server
